title: anarsamadov.github.io
subtitle: being normal is boring ;)
author:
  name: Anar Samadov
email: anar@samadov.net
description: Fullstack developer # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anarsamadov.github.io" # the base hostname & protocol for your site, e.g. http://example.com
ga_id: UA-31581333-23


include: ["_pages"]
show_excerpts: true
paginate: 1
paginate_path: "/blog/page:num/"

collections:
  blog:
    permalink: '/blog/:path/'

# Build settings
theme: minima
minima:
  skin: "classic"
  social_links:
    facebook: anar.samadov
    twitter: anarsamadov
    github: anarsamadov
    youtube:
    linkedin: anarsamadov

# PLUGINS
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# COMPRESS
compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

